source ~/Dropbox/coding/coding/culture/mac/settings/bashrc
source ~/Dropbox/coding/coding/culture/mac/settings/env_variables
source ~/Dropbox/coding/coding/culture/mac/settings/Joe_Settings_Aliases
source ~/Dropbox/coding/coding/culture/mac/settings/Joe_Settings_Functions


export PATH="$HOME/.rbenv/bin:$PATH"

eval "$(rbenv init -)"
