source /Users/user/coding/culture/mac/settings/bashrc
source /Users/user/coding/culture/mac/settings/Joe_Settings_Aliases
source /Users/user/coding/culture/mac/settings/Joe_Settings_Functions
source /Users/user/coding/culture/mac/settings/env_variables

eval "$(rbenv init -)"
