
[[ -s "/Users/apprentice/.rvm/scripts/rvm" ]] && source "/Users/apprentice/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
source ~/.git-completion.bash
PS1='\h:\W$(__git_ps1 " (%s)")\$ '
export PS1='\[\033[01;33m\]\u@\h\[\033[01;31m\] \W$(__git_ps1 " (%s)") \$\[\033[00m\] '
export LSCOLORS=ExGxFxdxCxDxDxaccxaeex

export PATH="/usr/local/bin:$PATH"

alias ls='ls -FG'
source ~/Dropbox/DBC-Chicago/Squirrels/Dmitri\ Rakhuba/things/culture.sh
