[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# ******JOE_ADDED ********************************
source ~/Dropbox/coding/coding/culture/mac/settings/Joe_Settings_Functions
source ~/Dropbox/coding/coding/culture/mac/settings/Joe_Settings_Aliases

#source ~/dbc/culture/culture/Joe_Settings_aliases_WIP

PATH="~/Dropbox/coding/culture/:$PATH"
#****************************************************


# function subl()
# {
# 	sublime-text $@ &
# 	exit 0
# }
